import { test, expect } from '@playwright/test';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, resolve } from 'node:path';

const root=resolve(import.meta.dirname,'..'),frozen=resolve(root,'e2e/fixtures/v15-frozen');
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png','.webp':'image/webp','.wav':'audio/wav'};
let server,origin,release=false;
test.beforeAll(async()=>{server=createServer(async(request,response)=>{if(request.url==='/__switch'&&request.method==='POST'){release=true;response.writeHead(204);response.end();return;}const pathname=decodeURIComponent(new URL(request.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\//,''),base=release?root:frozen,path=resolve(base,relative);if(!path.startsWith(base)){response.writeHead(403);response.end();return;}try{const body=await readFile(path);response.writeHead(200,{'content-type':mime[extname(path)]??'application/octet-stream','cache-control':'no-store'});response.end(body);}catch{response.writeHead(404);response.end('not found');}});await new Promise(resolveListen=>server.listen(0,'127.0.0.1',resolveListen));origin=`http://127.0.0.1:${server.address().port}`;});
test.afterAll(async()=>{await new Promise(resolveClose=>server.close(resolveClose));});

test('upgrades an actual V15 controller/cache to V16 and reloads offline',async({browser})=>{
 const context=await browser.newContext(),page=await context.newPage();await page.goto(origin);await page.evaluate(()=>{localStorage.setItem('troy_last_phalanx_v14_meta',JSON.stringify({schemaVersion:15,hero:'archer',difficulty:'heroic',curses:['fire'],might:3,settings:{quality:'high'}}));return navigator.serviceWorker.ready;});await page.reload();
 const before=await page.evaluate(async()=>({controlled:!!navigator.serviceWorker.controller,caches:await caches.keys()}));expect(before.controlled).toBe(true);expect(before.caches.some(name=>name.includes('v15'))).toBe(true);
 await context.request.post(`${origin}/__switch`);await page.evaluate(async()=>{const registration=await navigator.serviceWorker.getRegistration();const changed=new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true}));await registration.update();await changed;});
 await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await expect.poll(()=>page.evaluate(()=>window.__TROY_V16_READY__?.schemaVersion)).toBe(16);await expect.poll(()=>page.evaluate(()=>window.__TROY_V16_READY__?.serviceWorker)).toBe(true);await expect.poll(()=>page.evaluate(()=>window.__TROY_BOOT__?.status)).toBe('ready');
 const after=await page.evaluate(async()=>{const names=await caches.keys(),active=names.find(name=>name.includes('v16')),urls=active?await caches.open(active).then(cache=>cache.keys()).then(keys=>keys.map(key=>new URL(key.url).pathname).sort()):[],manifest=await fetch('./v16-release-manifest.json').then(response=>response.json()),expected=manifest.urls.map(url=>new URL(url,location.href).pathname).sort(),save=JSON.parse(localStorage.getItem('troy_save_v16'));return{controller:!!navigator.serviceWorker.controller,names,urls,expected,save};});expect(after.controller).toBe(true);expect(after.names).toEqual(['troy-last-phalanx-v16-rich-1']);expect(after.urls.some(path=>path.includes('game-v15'))).toBe(true);expect(after.urls).toEqual(after.expected);expect(after.save.schemaVersion).toBe(16);expect(after.save.hero).toBe('archer');await context.close();
});
