import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const projectRoot = resolve(import.meta.dirname, '..');
const EXPECTED = Object.freeze({
  'ricardo-foundry/canvas-vampire-survivors': ['e616704889e57efc9c1f49098786a95c364008d3', 'd4f9402cbb8a46777fe59930678968228e381cec7f06cb27f38668f16a03ccab'],
  'FreePeak/opencombat': ['aad6c51adbe6d89254b2302c7742449090596b86', '470f2c0915b1d404a53f3a35c7fde9d447091b8005571f823548d8ce3c0f0940'],
  'dknos/kitty-kaki-survivors': ['411c1968d31688f19f8f80d09eebae90b1e27ca9', 'fbd0f3583f13608939e8e9e904c92492b72a50a3e9cb01596778c76756fd5244'],
  'risingore/gear-arena': ['bd1fc80261153ce9295bb603121f9cdbd6329d74', '38848eb46580e2c61a28046ae2b1fb9ccbf1d5231c6db12b2bc7a74cde461dc9'],
});

function readJson(root, name) { return JSON.parse(readFileSync(resolve(root, name), 'utf8')); }

// @MX:ANCHOR: [AUTO] Final release gate for every researched repository and runtime audio source.
// @MX:REASON: Cutover, CI, and mutation tests must enforce one provenance policy.
export function validateSiegeLicenses(root = projectRoot, overrides = {}) {
  const notice = overrides.notice ?? readJson(root, 'third-party-source-notice-v16.json');
  const audioAllowlist = overrides.audioAllowlist ?? readJson(root, 'audio-source-allowlist-v16.json');
  const failures = [];
  for (const [repository, [revision, licenseSha256]] of Object.entries(EXPECTED)) {
    const item = notice.repositories?.find(candidate => candidate.repository === repository);
    if (!item) { failures.push(`${repository}: repository expected=present actual=missing`); continue; }
    if (item.revision !== revision) failures.push(`${repository}: revision expected=${revision} actual=${item.revision}`);
    if (item.licenseSha256 !== licenseSha256) failures.push(`${repository}: licenseSha256 expected=${licenseSha256} actual=${item.licenseSha256}`);
    for (const path of item.copiedPaths ?? []) failures.push(`${repository}: path expected=deny actual=${path}`);
  }
  for (const item of audioAllowlist.assets ?? []) failures.push(`${item.id}: path expected=deny actual=${item.path}; hash=${item.sha256}`);
  if (notice.repositories?.length !== 4) failures.push(`repositories expected=4 actual=${notice.repositories?.length ?? 0}`);
  if (failures.length) throw new Error(failures.join('\n'));
  return { repositories: 4, externalAudioAssets: 0, deniedPaths: 0 };
}

export function sha256File(path) { return createHash('sha256').update(readFileSync(path)).digest('hex'); }

const AUDIO_RULES=Object.freeze({
 music_field_base:['music',true,60000],music_boss_base:['music',true,60000],music_critical_layer:['music',true,30000],
 ambient_shore_waves:['ambient',true,30000],ambient_plain_wind:['ambient',true,30000],ambient_city_fire:['ambient',true,30000],ambient_crowd_distant:['ambient',true,30000],
 sfx_parry_shield:['combat',false,120],sfx_parry_sword:['combat',false,120],sfx_parry_bow:['combat',false,120],sfx_dodge_start:['combat',false,150],sfx_dodge_land:['combat',false,120],
 sfx_weapon_spear:['combat',false,100],sfx_weapon_sword:['combat',false,100],sfx_weapon_bow:['combat',false,100],sfx_weapon_shield:['combat',false,100],sfx_crowd_charge:['ambient',false,500],sfx_fire_burst:['combat',false,300],sfx_wind_gust:['ambient',false,500],cue_boss_intro:['ui',false,800],cue_boss_enrage:['ui',false,600],cue_boss_defeat:['ui',false,900],
});
export const REQUIRED_AUDIO_IDS=Object.freeze(Object.keys(AUDIO_RULES).sort());
const COMMON=['id','path','bus','loop','sourceClass','sha256','durationMs','sampleRate','channels','truePeakDbfs','eventMap'];
function wavMetrics(buffer){if(buffer.toString('ascii',0,4)!=='RIFF'||buffer.toString('ascii',8,12)!=='WAVE')throw new Error('expected=PCM WAV actual=invalid');const channels=buffer.readUInt16LE(22),sampleRate=buffer.readUInt32LE(24),bits=buffer.readUInt16LE(34),bytes=buffer.readUInt32LE(40),count=bytes/(bits/8)/channels;let peak=0,first=0,last=0;for(let offset=44,index=0;offset<44+bytes;offset+=2,index++){const sample=buffer.readInt16LE(offset)/32767;if(index===0)first=sample;last=sample;peak=Math.max(peak,Math.abs(sample));}return{channels,sampleRate,sampleCount:count,durationMs:Math.round(count/sampleRate*1000),truePeakDbfs:20*Math.log10(Math.max(peak,1e-9)),seamDelta:Math.abs(first-last)};}

// @MX:ANCHOR: [AUTO] Runtime files and declared audio quality share this measured manifest gate.
// @MX:REASON: Release validation and mutation tests must reject metadata that does not match WAV bytes.
export function validateAudioManifest(root=projectRoot,overrides={}){
 const manifest=overrides.manifest??readJson(root,'assets/audio/v16/audio-manifest.json'),failures=[];if(Object.keys(manifest).sort().join(',')!=='assets,schemaVersion')failures.push('manifest properties expected=assets,schemaVersion');
 const ids=(manifest.assets??[]).map(a=>a.id).sort(),missing=REQUIRED_AUDIO_IDS.filter(id=>!ids.includes(id)),extra=ids.filter(id=>!REQUIRED_AUDIO_IDS.includes(id));if(missing.length)failures.push(`missing=${missing.join(',')}`);if(extra.length)failures.push(`extra=${extra.join(',')}`);
 for(const asset of manifest.assets??[]){const rule=AUDIO_RULES[asset.id];if(!rule)continue;for(const property of COMMON)if(asset[property]===undefined)failures.push(`${asset.id}: property expected=${property} actual=missing`);const allowed=new Set([...COMMON,'author','provenanceNote',...(asset.loop?['loopStartSample','loopEndSample','seamDelta']:[])]);for(const property of Object.keys(asset))if(!allowed.has(property))failures.push(`${asset.id}: ${property} expected=forbidden actual=present`);if(asset.sourceClass!=='original')failures.push(`${asset.id}: sourceClass expected=original actual=${asset.sourceClass}`);if(!asset.author||!asset.provenanceNote)failures.push(`${asset.id}: property expected=author/provenanceNote actual=missing`);if(asset.sourceUrl!==undefined)failures.push(`${asset.id}: sourceUrl expected=forbidden actual=present`);if(asset.bus!==rule[0]||asset.loop!==rule[1])failures.push(`${asset.id}: bus/loop expected=${rule[0]}/${rule[1]} actual=${asset.bus}/${asset.loop}`);if(asset.durationMs<rule[2])failures.push(`${asset.id}: durationMs expected>=${rule[2]} actual=${asset.durationMs}`);if(![44100,48000].includes(asset.sampleRate))failures.push(`${asset.id}: sampleRate expected=44100|48000 actual=${asset.sampleRate}`);if(![1,2].includes(asset.channels))failures.push(`${asset.id}: channels expected=1|2 actual=${asset.channels}`);if(!Array.isArray(asset.eventMap)||asset.eventMap.length===0)failures.push(`${asset.id}: eventMap expected=non-empty actual=${asset.eventMap}`);if(!/^[0-9a-f]{64}$/.test(asset.sha256??''))failures.push(`${asset.id}: sha256 expected=64hex actual=${asset.sha256}`);if(asset.truePeakDbfs>-1)failures.push(`${asset.id}: truePeakDbfs expected<=-1 actual=${asset.truePeakDbfs}`);for(const p of ['loopStartSample','loopEndSample','seamDelta'])if(asset.loop?(asset[p]===undefined):(asset[p]!==undefined))failures.push(`${asset.id}: ${p} expected=${asset.loop?'present':'forbidden'} actual=${asset[p]}`);if(asset.loop&&asset.seamDelta>.02)failures.push(`${asset.id}: seamDelta expected<=0.02 actual=${asset.seamDelta}`);
  if(!overrides.manifest){const path=resolve(root,asset.path),buffer=readFileSync(path),metrics=wavMetrics(buffer);if(sha256File(path)!==asset.sha256)failures.push(`${asset.id}: sha256 expected=${asset.sha256} actual=${sha256File(path)}`);for(const p of ['sampleRate','channels','durationMs'])if(metrics[p]!==asset[p])failures.push(`${asset.id}: ${p} expected=${asset[p]} actual=${metrics[p]}`);if(metrics.truePeakDbfs>-1||asset.truePeakDbfs>-1)failures.push(`${asset.id}: truePeakDbfs expected<=-1 actual=${metrics.truePeakDbfs}`);if(asset.loop&&(metrics.seamDelta>.02||asset.seamDelta>.02))failures.push(`${asset.id}: seamDelta expected<=0.02 actual=${metrics.seamDelta}`);}
 }
 if(failures.length)throw new Error(failures.join('\n'));return{assets:ids.length,ids};
}

const BOSS_EXPECTED=Object.freeze({
 'paris/retreat-shot':['away-strafe-160',360,'reflectable',650,700,'high','1,2,3',72],'paris/triple-arrow':['fixed-aim',420,'reflectable',800,900,'high','1,2,3',72],'paris/falling-line':['clockwise-orbit-90',300,'dodgeOnly',1100,1200,'high','2,3',80],
 'sarpedon/lance-charge':['line-420',260,'parryable',700,900,'high','1,2,3',96],'sarpedon/circle-shock':['stationary',150,'dodgeOnly',900,1000,'high','1,2,3',96],'sarpedon/wing-sweep':['semicircle-180',190,'parryable',750,1100,'high','2,3',96],
 'chariot/outer-orbit':['orbit-240',280,'parryable',600,800,'high','1,2,3',112],'chariot/piercing-charge':['line-560',340,'dodgeOnly',850,1200,'high','1,2,3',112],'chariot/wheel-shard':['decelerate-180',260,'reflectable',950,1000,'high','2,3',112],
 'aeneas/shield-advance':['toward-180',160,'parryable',650,850,'high','1,2,3',88],'aeneas/phalanx-fan':['facing-lock',300,'reflectable',900,1100,'high','1,2,3',88],'aeneas/standard-wave':['retreat-120',210,'dodgeOnly',1050,1250,'high','2,3',96],
 'penthesilea/flank-slash':['cross-260',150,'parryable',550,650,'high','1,2,3',80],'penthesilea/leap-land':['arc-300',180,'dodgeOnly',900,1000,'high','1,2,3',96],'penthesilea/javelin-ring':['orbit-120',320,'reflectable',1000,1150,'high','2,3',80],
 'memnon/sun-advance':['toward-150',190,'parryable',700,850,'high','1,2,3',96],'memnon/sun-beam':['sweep-45',380,'dodgeOnly',1100,1300,'high','1,2,3',96],'memnon/earth-slam':['stationary',220,'unavoidable',1400,1500,'high','3',112],
 'hector/shield-pressure':['toward-200',140,'parryable',600,750,'high','1,2,3',96],'hector/spear-charge':['line-480',320,'dodgeOnly',850,1050,'high','1,2,3',112],'hector/last-combo':['combo-160-220',200,'sub-intent',0,1400,'high','3',112],
});
const BOSS_FIELDS=['movement','distance','tag','telegraphMs','recoveryMs','threat','phases','inset'];
export function validateBossManifest(root=projectRoot,overrides={}){const manifest=overrides.manifest??readJson(root,'assets/bosses/troy-boss-fsm-v16.json'),failures=[];if(manifest.bosses?.length!==7)failures.push(`bosses expected=7 actual=${manifest.bosses?.length??0}`);if((manifest.states??[]).join(',')!=='approach,windup,attack,recovery,enrage,stagger,dead')failures.push(`states expected=7 canonical actual=${(manifest.states??[]).join(',')}`);for(const boss of manifest.bosses??[])for(const pattern of boss.patterns??[]){const key=`${boss.id}/${pattern.id}`,expected=BOSS_EXPECTED[key];if(!expected){failures.push(`${key}: expected=known actual=extra`);continue;}const actual=[pattern.movement,pattern.distance,pattern.tag,pattern.telegraphMs,pattern.recoveryMs,pattern.threat,pattern.phases.join(','),pattern.inset];actual.forEach((value,index)=>{if(value!==expected[index])failures.push(`${key}: ${BOSS_FIELDS[index]} expected=${expected[index]} actual=${value}`);});}const paths=(manifest.bosses??[]).flatMap(item=>item.patterns.map(pattern=>`${item.id}/${pattern.id}`));for(const key of Object.keys(BOSS_EXPECTED))if(!paths.includes(key))failures.push(`${key}: expected=present actual=missing`);const source=readFileSync(resolve(root,'js/boss-fsm-v16.js'),'utf8'),forbidden=[...source.matchAll(/\b(?:Date\.now|performance\.now|Math\.random|setTimeout|setInterval|requestAnimationFrame)\s*\(/g)].map(match=>match[0]);if(forbidden.length)failures.push(`boss reducer forbidden APIs actual=${forbidden.join(',')}`);if(failures.length)throw new Error(failures.join('\n'));return{bosses:7,patterns:paths.length,states:7,forbiddenApis:0};}
export function validateListeningEvidence(root=projectRoot){let rows;try{rows=readJson(root,'audio-listening-v16.json');}catch{throw new Error('listening evidence unobserved: audio-listening-v16.json is absent');}const loops=['music_field_base','music_boss_base','music_critical_layer','ambient_shore_waves','ambient_plain_wind','ambient_city_fire','ambient_crowd_distant'],failures=[];for(const id of loops)for(const device of ['headphones','speakers']){const row=rows.find(item=>item.audioId===id&&item.device===device);if(!row)failures.push(`${id}/${device}: listening evidence unobserved`);else for(const finding of ['seamClick','cueMasking','clipping'])if(row[finding]!==0)failures.push(`${id}/${device}: ${finding} expected=0 actual=${row[finding]}`);}if(failures.length)throw new Error(failures.join('\n'));return{rows:rows.length,loops:loops.length};}
export function validateScriptGraph(root=projectRoot,overrides={}){const packageJson=overrides.packageJson??readJson(root,'package.json'),scripts=packageJson.scripts??{},graph={};for(const[name,command]of Object.entries(scripts)){const edges=[];for(const match of command.matchAll(/\bnpm\s+(?:run\s+([\w:-]+)|test\b)/g))edges.push(match[1]??'test');graph[name]=edges.filter(edge=>scripts[edge]);}const visited=new Set(),active=[],cycles=[];function visit(name){const at=active.indexOf(name);if(at>=0){cycles.push([...active.slice(at),name]);return;}if(visited.has(name))return;active.push(name);for(const next of graph[name]??[])visit(next);active.pop();visited.add(name);}for(const name of Object.keys(graph))visit(name);if(cycles.length)throw new Error(`script cycle: ${cycles[0].join(' -> ')}`);return{cycles:0};}

export const FINAL_TEST_AGGREGATE='npm run test:v15-frozen && npm run test:v16:combat && npm run test:v16:campaign && npm run test:v16:siege && npm run test:v16:rich && npm run test:boss && npm run check:v16:coverage-contract && npm run coverage:v16:rich && npm run check:v16:rich';
export const FINAL_VERIFY_AGGREGATE='node tools/create-rich-handoff-v16.mjs --root . --release-evidence baselines/v16-rich-release.json --run-gate-profile rich-final --gate-output .moai/reports/SPEC-TROY-RICH-INTEGRATION-020/release-gates.json';
export function validateCandidateScriptGraph(root=projectRoot,{packagePath='package.json',candidateKey='test'}={}){const packageJson=readJson(root,packagePath),aggregate=candidateKey==='verify:v16:rich'?FINAL_VERIFY_AGGREGATE:FINAL_TEST_AGGREGATE;packageJson.scripts={...packageJson.scripts,[candidateKey]:aggregate};try{return validateScriptGraph(root,{packageJson});}catch(error){const path=error.message.replace(/^script cycle:\s*/, '');throw new Error(`SCRIPT_GRAPH_CYCLE: ${path}`);}}
export function validateReleaseManifest(root=projectRoot,overrides={}){const manifest=overrides.manifest??readJson(root,'v16-release-manifest.json'),urls=manifest.urls??[],duplicates=urls.length-new Set(urls).size,failures=[];if(duplicates)failures.push(`release urls duplicates expected=0 actual=${duplicates}`);for(const url of urls){if(url==='./')continue;const relative=url.replace(/^\.\//,'');if(!existsSync(resolve(root,relative)))failures.push(`release path expected=present actual=missing path=${relative}`);}const audioIds=urls.filter(url=>/^\.\/assets\/audio\/v16\/[^/]+\.wav$/.test(url)).map(url=>url.split('/').at(-1).replace(/\.wav$/,'')).sort(),missing=REQUIRED_AUDIO_IDS.filter(id=>!audioIds.includes(id)),extra=audioIds.filter(id=>!REQUIRED_AUDIO_IDS.includes(id));if(missing.length||extra.length)failures.push(`release audio missing=${missing.join(',')} extra=${extra.join(',')}`);if(manifest.cacheName!=='troy-last-phalanx-v16-rich-4')failures.push(`cacheName expected=troy-last-phalanx-v16-rich-4 actual=${manifest.cacheName}`);if(!urls.includes('./js/game.js')||urls.some(url=>/(?:index-v\d+\.html|js\/game-v\d+\.js)/.test(url)))failures.push('release runtime expected=js/game.js only');if(failures.length)throw new Error(failures.join('\n'));return{missingFiles:0,audioAssets:audioIds.length,duplicates:0,urls:urls.length};}

export function validateV15DefenseLeaf(root=projectRoot){const scripts=readJson(root,'package.json').scripts??{},expected='c8 --check-coverage --lines 90 --branches 90 --functions 90 --statements 90 node --test tests/defense-rules-v15.test.mjs && node --test tests/defense-assets-v15.test.mjs && node tools/validate-v15.mjs --root e2e/fixtures/v15-frozen',frozen='npm run test:defense && npm run test:run && node tools/validate-v15-frozen.mjs --root e2e/fixtures/v15-frozen && playwright test --project=v15-frozen';if(scripts['test:defense']!==expected)throw new Error(`V15_ROOT_ESCAPE: test:defense expected=${expected} actual=${scripts['test:defense']}`);if(scripts['test:v15-frozen']!==frozen)throw new Error(`V15_ROOT_ESCAPE: test:v15-frozen expected=${frozen} actual=${scripts['test:v15-frozen']}`);return{defenseRoot:'frozen',frozenLeaf:'unchanged'};}
export function validateFrozenExpectTimeout(root=projectRoot,{source=null}={}){const text=source??readFileSync(resolve(root,'playwright.config.mjs'),'utf8'),lines=text.split(/\r?\n/),frozen=lines.find(line=>/name:\s*['"]v15-frozen['"]/.test(line))??'',combat=lines.find(line=>/name:\s*['"]v16-combat['"]/.test(line))??'',live=lines.find(line=>/name:\s*['"]v16-live['"]/.test(line))??'';if(!/expect:\s*\{\s*timeout:\s*10_000\s*\}/.test(frozen)||/\bexpect\s*:/.test(combat)||/\bexpect\s*:/.test(live))throw new Error('PLAYWRIGHT_FROZEN_TIMEOUT_MISMATCH: frozen expected=10000 combat/live expected=default');return{frozen:10000,combat:'default',live:'default'};}
export function validateRunnerSource(root=projectRoot,{source=null}={}){const text=source??readFileSync(resolve(root,'tools/run-playwright-v16.mjs'),'utf8');if(/\bnpx\b|shell\s*:\s*true/.test(text)||!/spawn\(process\.execPath/.test(text)||!/shell\s*:\s*false/.test(text))throw new Error('PLAYWRIGHT_RUNNER_SPAWN_MISMATCH: expected=process.execPath/direct/shell=false actual=mutation');if(!/NO_OPEN\s*:\s*['"]1['"]/.test(text))throw new Error('PLAYWRIGHT_SERVER_ISOLATION_MISMATCH: NO_OPEN expected=1 actual=missing');if(!/finally\s*\{|closeAllConnections\(\)|await close\(server\)|probeFree\(\)/.test(text))throw new Error('PLAYWRIGHT_RUNNER_CLEANUP_MISMATCH: expected=finally/close-await/probe actual=missing');if(!/process\.exitCode\s*=\s*code/.test(text)||!/return forcedExit \?\? childExit/.test(text))throw new Error('PLAYWRIGHT_RUNNER_EXIT_MISMATCH: expected=child exit propagation actual=missing');return{shell:false,noOpen:true,cleanup:true,exitPropagation:true};}
export function probeRunnerCleanup(root=projectRoot){const runner=resolve(root,'tools/run-playwright-v16.mjs'),result=spawnSync(process.execPath,[runner,'test','--project=v16-live','--grep','__V16_FORCED_FAILURE_PROBE__'],{cwd:root,encoding:'utf8',timeout:5000,windowsHide:true}),output=`${result.stdout??''}${result.stderr??''}`;if(result.error?.code==='ETIMEDOUT'||!output.includes('PLAYWRIGHT_V16_CLEANUP port4173=free childCount=0')||result.status===0)throw new Error(`PLAYWRIGHT_RUNNER_CLEANUP_MISMATCH: expected=nonzero/free/childCount0 actual=status:${result.status} ${result.error?.code??''}`);return{childExit:result.status,port4173:'free',childCount:0};}

function canonicalJson(value){if(Array.isArray(value))return value.map(canonicalJson);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonicalJson(value[key])]));return value;}
export function validateLockVersion(root=projectRoot,{lock=null,expectedContentSha256}={}){const packageJson=readJson(root,'package.json'),packageLock=structuredClone(lock??readJson(root,'package-lock.json'));const lockVersion=packageLock.version,workspaceVersion=packageLock.packages?.['']?.version;if(packageJson.version!=='16.0.0'||lockVersion!=='16.0.0'||workspaceVersion!=='16.0.0')throw new Error(`package-lock.json: version expected=16.0.0 actual=${lockVersion}/${workspaceVersion}; package.json=${packageJson.version}`);delete packageLock.version;delete packageLock.packages[''].version;const actual=createHash('sha256').update(JSON.stringify(canonicalJson(packageLock))).digest('hex');if(actual!==expectedContentSha256)throw new Error(`package-lock.json: content hash expected=${expectedContentSha256} actual=${actual}`);return{packageVersion:packageJson.version,lockVersion,contentSha256:actual};}

export function validatePlaywrightRouting(root=projectRoot,{configSource=null}={}){const source=configSource??readFileSync(resolve(root,'playwright.config.mjs'),'utf8'),failures=[];for(const name of ['v15-frozen','v16-live']){const count=(source.match(new RegExp(`name:\\s*['\"]${name}['\"]`,'g'))??[]).length;if(count!==1)failures.push(`playwright.config.mjs: ${name} expected=1 actual=${count}`);}if(/name:\s*['"](?:v15-live|v16-combat)['"]/.test(source))failures.push('playwright.config.mjs: alternate live project expected=absent actual=present');if(!/workers:\s*1\b/.test(source))failures.push('playwright.config.mjs: workers expected=1');for(const [pattern,count] of [['v15-frozen-suite\\\\\.spec\\\\\.mjs',1],['v15-v16-upgrade\\|v16-rich-journey\\|v16-rich-offline',1]]){const actual=(source.match(new RegExp(pattern,'g'))??[]).length;if(actual!==count)failures.push(`playwright.config.mjs: route pattern expected=${count} actual=${actual}`);}for(const port of ['4173','4175'])if(!source.includes(port))failures.push(`playwright.config.mjs: port expected=${port} actual=missing`);const wrapper=readFileSync(resolve(root,'e2e/v15-frozen-suite.spec.mjs'),'utf8'),imports=[...wrapper.matchAll(/import\s+['"]\.\/([^'"]+\.spec\.mjs)['"]/g)].map(match=>match[1]);const expectedImports=['defense-v15.spec.mjs','troy-run-fixed-v15.spec.mjs','troy-run-v15.spec.mjs','v15-debt-closure.spec.mjs'];if(imports.sort().join(',')!==expectedImports.sort().join(','))failures.push(`e2e/v15-frozen-suite.spec.mjs: imports expected=${expectedImports.length} actual=${imports.length}`);if(failures.length)throw new Error(failures.join('\n'));return{projects:2,directMatches:5,sourceMembership:1+imports.length+4,workers:1};}

let specialCliHandled=false;
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)&&process.argv.includes('--check-v15-defense-leaf')){try{const result=validateV15DefenseLeaf(projectRoot);console.log(`V15 defense leaf: PASS (root=${result.defenseRoot}, frozenLeaf=${result.frozenLeaf})`);}catch(error){console.error(`V16 license gate: FAIL\n${error.message}`);process.exitCode=1;}specialCliHandled=true;}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)&&process.argv.includes('--playwright-routing')){try{const config=readFileSync(resolve(projectRoot,'playwright.config.mjs'),'utf8');if(/\bwebServer\s*:/.test(config))throw new Error('PLAYWRIGHT_SERVER_OWNERSHIP_MISMATCH: webServer expected=absent actual=present');validateFrozenExpectTimeout(projectRoot,{source:config});validateRunnerSource(projectRoot);if(process.argv.includes('--probe-cleanup')){const probe=probeRunnerCleanup(projectRoot);console.log(`V16 runner cleanup: PASS (port4173=${probe.port4173}, childCount=${probe.childCount}, childExit=${probe.childExit})`);}}catch(error){console.error(`V16 license gate: FAIL\n${error.message}`);process.exitCode=1;specialCliHandled=true;}}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url) && !specialCliHandled) {
  try { if(process.argv.includes('--check-script-graph')){const flagAt=process.argv.indexOf('--check-script-graph'),packagePath=process.argv[flagAt+1]??'package.json',candidateAt=process.argv.indexOf('--candidate-aggregate'),candidateKey=candidateAt>=0?process.argv[candidateAt+1]:'test';const graph=validateCandidateScriptGraph(projectRoot,{packagePath,candidateKey});console.log(`V16 script graph: PASS (cycles=${graph.cycles})`);}else if(process.argv.includes('--playwright-routing')){const result=validatePlaywrightRouting(projectRoot);console.log(`V16 Playwright routing: PASS (projects=${result.projects}, directMatches=${result.directMatches}, sourceMembership=${result.sourceMembership})`);}else if(process.argv.includes('--check-lock-version')){const expectedAt=process.argv.indexOf('--expected-lock-content-sha256'),expectedContentSha256=process.argv[expectedAt+1];const result=validateLockVersion(projectRoot,{expectedContentSha256});console.log(`V16 lock version: PASS (version=${result.lockVersion}, contentSha256=${result.contentSha256})`);}else{const result=validateSiegeLicenses(projectRoot),audio=process.argv.includes('--audio')?validateAudioManifest(projectRoot):null,bosses=process.argv.includes('--boss')?validateBossManifest(projectRoot):null,release=process.argv.includes('--release')?validateReleaseManifest(projectRoot):null,listening=process.argv.includes('--listening')?validateListeningEvidence(projectRoot):null;validateScriptGraph(projectRoot);console.log(`V16 final validator: PASS (repositories=${result.repositories}${audio?`, audio=${audio.assets}`:''}${bosses?`, bosses=${bosses.bosses}, patterns=${bosses.patterns}`:''}${release?`, releaseUrls=${release.urls}`:''}${listening?`, listeningRows=${listening.rows}`:''}, scriptCycles=0)`);} }
  catch (error) { console.error(`V16 license gate: FAIL\n${error.message}`); process.exitCode = 1; }
}
